name = "samir-kumar-backend"
main = "src/index.ts"
compatibility_date = "2023-12-01"
account_id = "dedcb339ae411669d19772f5d3243f35"


[[d1_databases]]
binding = "DB"
database_name = "careerskope-prod"
database_id = "2d8b5fa2-941d-4837-911d-089e53994a91"
